/*
  The MIT License (MIT)
  Copyright © 2016 Steve Guidetti

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the “Software”), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/
namespace Elementary.Model
{
    /// <summary>
    /// Represents an Element.
    /// </summary>
    public class Element
    {
        /// <summary>
        /// The element number.
        /// </summary>
        public long Number { get; internal set; }

        /// <summary>
        /// The element symbol.
        /// </summary>
        public string Symbol { get; internal set; }

        /// <summary>
        /// The element group.
        /// </summary>
        public long Group { get; internal set; }

        /// <summary>
        /// The element period.
        /// </summary>
        public long Period { get; internal set; }

        /// <summary>
        /// The element block.
        /// </summary>
        public string Block { get; internal set; }

        /// <summary>
        /// The atomic weight of the element.
        /// </summary>
        public double Weight { get; internal set; }

        /// <summary>
        /// The density of the element in g/cm³.
        /// </summary>
        public double? Density { get; internal set; }

        /// <summary>
        /// The melting point of the element in K.
        /// </summary>
        public double? Melt { get; internal set; }

        /// <summary>
        /// The boiling point of the element in K.
        /// </summary>
        public double? Boil { get; internal set; }

        /// <summary>
        /// The heat of the element in J/g·K.
        /// </summary>
        public double? Heat { get; internal set; }

        /// <summary>
        /// The electronegativity of the element in V.
        /// </summary>
        public double? Negativity { get; internal set; }

        /// <summary>
        /// The abundance of the element in mg/kg.
        /// </summary>
        public double? Abundance { get; internal set; }

        /// <summary>
        /// The element category.
        /// </summary>
        public long Category { get; internal set; }

        /// <summary>
        /// The electron configuration of the element.
        /// </summary>
        public string Configuration { get; internal set; }

        /// <summary>
        /// The electrons per shell of the element.
        /// </summary>
        public string Electrons { get; internal set; }

        /// <summary>
        /// Whether the element is unstable.
        /// </summary>
        public bool Unstable { get; internal set; }

        /// <summary>
        /// List of all of the elements.
        /// </summary>
        public static Element[] List { get; } = new Element[]
        {
            new Element {
                Number = 1,
                Symbol = "H",
                Group = 1,
                Period = 1,
                Block = "s",
                Weight = 1.00794,
                Density = 0.00008988,
                Melt = 14.01,
                Boil = 20.28,
                Heat = 14.304,
                Negativity = 2.2,
                Abundance = 1400.0,
                Category = 0,
                Configuration = "1s1",
                Electrons = "1",
                Unstable = false,
            },
            new Element {
                Number = 2,
                Symbol = "He",
                Group = 18,
                Period = 1,
                Block = "s",
                Weight = 4.002602,
                Density = 0.0001785,
                Melt = 0.95,
                Boil = 4.22,
                Heat = 5.193,
                Negativity = null,
                Abundance = 0.008,
                Category = 1,
                Configuration = "1s2",
                Electrons = "2",
                Unstable = false,
            },
            new Element {
                Number = 3,
                Symbol = "Li",
                Group = 1,
                Period = 2,
                Block = "s",
                Weight = 6.941,
                Density = 0.534,
                Melt = 453.69,
                Boil = 1615.0,
                Heat = 3.582,
                Negativity = 0.98,
                Abundance = 20.0,
                Category = 2,
                Configuration = "1s2 2s1",
                Electrons = "2,1",
                Unstable = false,
            },
            new Element {
                Number = 4,
                Symbol = "Be",
                Group = 2,
                Period = 2,
                Block = "s",
                Weight = 9.012182,
                Density = 1.85,
                Melt = 1560.0,
                Boil = 2742.0,
                Heat = 1.825,
                Negativity = 1.57,
                Abundance = 2.8,
                Category = 3,
                Configuration = "1s2 2s2",
                Electrons = "2,2",
                Unstable = false,
            },
            new Element {
                Number = 5,
                Symbol = "B",
                Group = 13,
                Period = 2,
                Block = "p",
                Weight = 10.811,
                Density = 2.34,
                Melt = 2349.0,
                Boil = 4200.0,
                Heat = 1.026,
                Negativity = 2.04,
                Abundance = 10.0,
                Category = 4,
                Configuration = "1s2 2s2 2p1",
                Electrons = "2,3",
                Unstable = false,
            },
            new Element {
                Number = 6,
                Symbol = "C",
                Group = 14,
                Period = 2,
                Block = "p",
                Weight = 12.0107,
                Density = 2.267,
                Melt = 3823.0,
                Boil = 4300.0,
                Heat = 0.709,
                Negativity = 2.55,
                Abundance = 200.0,
                Category = 0,
                Configuration = "1s2 2s2 2p2",
                Electrons = "2,4",
                Unstable = false,
            },
            new Element {
                Number = 7,
                Symbol = "N",
                Group = 15,
                Period = 2,
                Block = "p",
                Weight = 14.0067,
                Density = 0.0012506,
                Melt = 63.15,
                Boil = 77.36,
                Heat = 1.04,
                Negativity = 3.04,
                Abundance = 19.0,
                Category = 0,
                Configuration = "1s2 2s2 2p3",
                Electrons = "2,5",
                Unstable = false,
            },
            new Element {
                Number = 8,
                Symbol = "O",
                Group = 16,
                Period = 2,
                Block = "p",
                Weight = 15.9994,
                Density = 0.001429,
                Melt = 54.36,
                Boil = 90.2,
                Heat = 0.918,
                Negativity = 3.44,
                Abundance = 461000.0,
                Category = 0,
                Configuration = "1s2 2s2 2p4",
                Electrons = "2,6",
                Unstable = false,
            },
            new Element {
                Number = 9,
                Symbol = "F",
                Group = 17,
                Period = 2,
                Block = "p",
                Weight = 18.9984032,
                Density = 0.001696,
                Melt = 53.53,
                Boil = 85.03,
                Heat = 0.824,
                Negativity = 3.98,
                Abundance = 585.0,
                Category = 5,
                Configuration = "1s2 2s2 2p5",
                Electrons = "2,7",
                Unstable = false,
            },
            new Element {
                Number = 10,
                Symbol = "Ne",
                Group = 18,
                Period = 2,
                Block = "p",
                Weight = 20.1797,
                Density = 0.0008999,
                Melt = 24.56,
                Boil = 27.07,
                Heat = 1.03,
                Negativity = null,
                Abundance = 0.005,
                Category = 1,
                Configuration = "1s2 2s2 2p6",
                Electrons = "2,8",
                Unstable = false,
            },
            new Element {
                Number = 11,
                Symbol = "Na",
                Group = 1,
                Period = 3,
                Block = "s",
                Weight = 22.98976928,
                Density = 0.971,
                Melt = 370.87,
                Boil = 1156.0,
                Heat = 1.228,
                Negativity = 0.93,
                Abundance = 23600.0,
                Category = 2,
                Configuration = "[Ne] 3s1",
                Electrons = "2,8,1",
                Unstable = false,
            },
            new Element {
                Number = 12,
                Symbol = "Mg",
                Group = 2,
                Period = 3,
                Block = "s",
                Weight = 24.305,
                Density = 1.738,
                Melt = 923.0,
                Boil = 1363.0,
                Heat = 1.023,
                Negativity = 1.31,
                Abundance = 23300.0,
                Category = 3,
                Configuration = "[Ne] 3s2",
                Electrons = "2,8,2",
                Unstable = false,
            },
            new Element {
                Number = 13,
                Symbol = "Al",
                Group = 13,
                Period = 3,
                Block = "p",
                Weight = 26.9815386,
                Density = 2.698,
                Melt = 933.47,
                Boil = 2792.0,
                Heat = 0.897,
                Negativity = 1.61,
                Abundance = 82300.0,
                Category = 6,
                Configuration = "[Ne] 3s2 3p1",
                Electrons = "2,8,3",
                Unstable = false,
            },
            new Element {
                Number = 14,
                Symbol = "Si",
                Group = 14,
                Period = 3,
                Block = "p",
                Weight = 28.0855,
                Density = 2.3296,
                Melt = 1687.0,
                Boil = 3538.0,
                Heat = 0.705,
                Negativity = 1.9,
                Abundance = 282000.0,
                Category = 4,
                Configuration = "[Ne] 3s2 3p2",
                Electrons = "2,8,4",
                Unstable = false,
            },
            new Element {
                Number = 15,
                Symbol = "P",
                Group = 15,
                Period = 3,
                Block = "p",
                Weight = 30.973762,
                Density = 1.82,
                Melt = 317.3,
                Boil = 553.6,
                Heat = 0.769,
                Negativity = 2.19,
                Abundance = 1050.0,
                Category = 0,
                Configuration = "[Ne] 3s2 3p3",
                Electrons = "2,8,5",
                Unstable = false,
            },
            new Element {
                Number = 16,
                Symbol = "S",
                Group = 16,
                Period = 3,
                Block = "p",
                Weight = 32.065,
                Density = 2.067,
                Melt = 388.36,
                Boil = 717.87,
                Heat = 0.71,
                Negativity = 2.58,
                Abundance = 350.0,
                Category = 0,
                Configuration = "[Ne] 3s2 3p4",
                Electrons = "2,8,6",
                Unstable = false,
            },
            new Element {
                Number = 17,
                Symbol = "Cl",
                Group = 17,
                Period = 3,
                Block = "p",
                Weight = 35.453,
                Density = 0.003214,
                Melt = 171.6,
                Boil = 239.11,
                Heat = 0.479,
                Negativity = 3.16,
                Abundance = 145.0,
                Category = 5,
                Configuration = "[Ne] 3s2 3p5",
                Electrons = "2,8,7",
                Unstable = false,
            },
            new Element {
                Number = 18,
                Symbol = "Ar",
                Group = 18,
                Period = 3,
                Block = "p",
                Weight = 39.948,
                Density = 0.0017837,
                Melt = 83.8,
                Boil = 87.3,
                Heat = 0.52,
                Negativity = null,
                Abundance = 3.5,
                Category = 1,
                Configuration = "[Ne] 3s2 3p6",
                Electrons = "2,8,8",
                Unstable = false,
            },
            new Element {
                Number = 19,
                Symbol = "K",
                Group = 1,
                Period = 4,
                Block = "s",
                Weight = 39.0983,
                Density = 0.862,
                Melt = 336.53,
                Boil = 1032.0,
                Heat = 0.757,
                Negativity = 0.82,
                Abundance = 20900.0,
                Category = 2,
                Configuration = "[Ar] 4s1",
                Electrons = "2,8,8,1",
                Unstable = false,
            },
            new Element {
                Number = 20,
                Symbol = "Ca",
                Group = 2,
                Period = 4,
                Block = "s",
                Weight = 40.078,
                Density = 1.54,
                Melt = 1115.0,
                Boil = 1757.0,
                Heat = 0.647,
                Negativity = 1.0,
                Abundance = 41500.0,
                Category = 3,
                Configuration = "[Ar] 4s2",
                Electrons = "2,8,8,2",
                Unstable = false,
            },
            new Element {
                Number = 21,
                Symbol = "Sc",
                Group = 3,
                Period = 4,
                Block = "d",
                Weight = 44.955912,
                Density = 2.989,
                Melt = 1814.0,
                Boil = 3109.0,
                Heat = 0.568,
                Negativity = 1.36,
                Abundance = 22.0,
                Category = 7,
                Configuration = "[Ar] 3d1 4s2",
                Electrons = "2,8,9,2",
                Unstable = false,
            },
            new Element {
                Number = 22,
                Symbol = "Ti",
                Group = 4,
                Period = 4,
                Block = "d",
                Weight = 47.867,
                Density = 4.54,
                Melt = 1941.0,
                Boil = 3560.0,
                Heat = 0.523,
                Negativity = 1.54,
                Abundance = 5650.0,
                Category = 7,
                Configuration = "[Ar] 3d2 4s2",
                Electrons = "2,8,10,2",
                Unstable = false,
            },
            new Element {
                Number = 23,
                Symbol = "V",
                Group = 5,
                Period = 4,
                Block = "d",
                Weight = 50.9415,
                Density = 6.11,
                Melt = 2183.0,
                Boil = 3680.0,
                Heat = 0.489,
                Negativity = 1.63,
                Abundance = 120.0,
                Category = 7,
                Configuration = "[Ar] 3d3 4s2",
                Electrons = "2,8,11,2",
                Unstable = false,
            },
            new Element {
                Number = 24,
                Symbol = "Cr",
                Group = 6,
                Period = 4,
                Block = "d",
                Weight = 51.9961,
                Density = 7.15,
                Melt = 2180.0,
                Boil = 2944.0,
                Heat = 0.449,
                Negativity = 1.66,
                Abundance = 102.0,
                Category = 7,
                Configuration = "[Ar] 3d5 4s1",
                Electrons = "2,8,13,1",
                Unstable = false,
            },
            new Element {
                Number = 25,
                Symbol = "Mn",
                Group = 7,
                Period = 4,
                Block = "d",
                Weight = 54.938045,
                Density = 7.44,
                Melt = 1519.0,
                Boil = 2334.0,
                Heat = 0.479,
                Negativity = 1.55,
                Abundance = 950.0,
                Category = 7,
                Configuration = "[Ar] 3d5 4s2",
                Electrons = "2,8,13,2",
                Unstable = false,
            },
            new Element {
                Number = 26,
                Symbol = "Fe",
                Group = 8,
                Period = 4,
                Block = "d",
                Weight = 55.845,
                Density = 7.874,
                Melt = 1811.0,
                Boil = 3134.0,
                Heat = 0.449,
                Negativity = 1.83,
                Abundance = 56300.0,
                Category = 7,
                Configuration = "[Ar] 3d6 4s2",
                Electrons = "2,8,14,2",
                Unstable = false,
            },
            new Element {
                Number = 27,
                Symbol = "Co",
                Group = 9,
                Period = 4,
                Block = "d",
                Weight = 58.933195,
                Density = 8.86,
                Melt = 1768.0,
                Boil = 3200.0,
                Heat = 0.421,
                Negativity = 1.88,
                Abundance = 25.0,
                Category = 7,
                Configuration = "[Ar] 3d7 4s2",
                Electrons = "2,8,15,2",
                Unstable = false,
            },
            new Element {
                Number = 28,
                Symbol = "Ni",
                Group = 10,
                Period = 4,
                Block = "d",
                Weight = 58.6934,
                Density = 8.912,
                Melt = 1728.0,
                Boil = 3186.0,
                Heat = 0.444,
                Negativity = 1.91,
                Abundance = 84.0,
                Category = 7,
                Configuration = "[Ar] 3d8 4s2",
                Electrons = "2,8,16,2",
                Unstable = false,
            },
            new Element {
                Number = 29,
                Symbol = "Cu",
                Group = 11,
                Period = 4,
                Block = "d",
                Weight = 63.546,
                Density = 8.96,
                Melt = 1357.77,
                Boil = 2835.0,
                Heat = 0.385,
                Negativity = 1.9,
                Abundance = 60.0,
                Category = 7,
                Configuration = "[Ar] 3d10 4s1",
                Electrons = "2,8,18,1",
                Unstable = false,
            },
            new Element {
                Number = 30,
                Symbol = "Zn",
                Group = 12,
                Period = 4,
                Block = "d",
                Weight = 65.38,
                Density = 7.134,
                Melt = 692.68,
                Boil = 1180.0,
                Heat = 0.388,
                Negativity = 1.65,
                Abundance = 70.0,
                Category = 7,
                Configuration = "[Ar] 3d10 4s2",
                Electrons = "2,8,18,2",
                Unstable = false,
            },
            new Element {
                Number = 31,
                Symbol = "Ga",
                Group = 13,
                Period = 4,
                Block = "p",
                Weight = 69.723,
                Density = 5.907,
                Melt = 302.9146,
                Boil = 2477.0,
                Heat = 0.371,
                Negativity = 1.81,
                Abundance = 19.0,
                Category = 6,
                Configuration = "[Ar] 3d10 4s2 4p1",
                Electrons = "2,8,18,3",
                Unstable = false,
            },
            new Element {
                Number = 32,
                Symbol = "Ge",
                Group = 14,
                Period = 4,
                Block = "p",
                Weight = 72.63,
                Density = 5.323,
                Melt = 1211.4,
                Boil = 3106.0,
                Heat = 0.32,
                Negativity = 2.01,
                Abundance = 1.5,
                Category = 4,
                Configuration = "[Ar] 3d10 4s2 4p2",
                Electrons = "2,8,18,4",
                Unstable = false,
            },
            new Element {
                Number = 33,
                Symbol = "As",
                Group = 15,
                Period = 4,
                Block = "p",
                Weight = 74.9216,
                Density = 5.776,
                Melt = 1090.0,
                Boil = 887.0,
                Heat = 0.329,
                Negativity = 2.18,
                Abundance = 1.8,
                Category = 4,
                Configuration = "[Ar] 3d10 4s2 4p3",
                Electrons = "2,8,18,5",
                Unstable = false,
            },
            new Element {
                Number = 34,
                Symbol = "Se",
                Group = 16,
                Period = 4,
                Block = "p",
                Weight = 78.96,
                Density = 4.809,
                Melt = 494.0,
                Boil = 958.0,
                Heat = 0.321,
                Negativity = 2.55,
                Abundance = 0.05,
                Category = 0,
                Configuration = "[Ar] 3d10 4s2 4p4",
                Electrons = "2,8,18,6",
                Unstable = false,
            },
            new Element {
                Number = 35,
                Symbol = "Br",
                Group = 17,
                Period = 4,
                Block = "p",
                Weight = 79.904,
                Density = 3.122,
                Melt = 265.8,
                Boil = 332.0,
                Heat = 0.474,
                Negativity = 2.96,
                Abundance = 2.4,
                Category = 5,
                Configuration = "[Ar] 3d10 4s2 4p5",
                Electrons = "2,8,18,7",
                Unstable = false,
            },
            new Element {
                Number = 36,
                Symbol = "Kr",
                Group = 18,
                Period = 4,
                Block = "p",
                Weight = 83.798,
                Density = 0.003733,
                Melt = 115.79,
                Boil = 119.93,
                Heat = 0.248,
                Negativity = 3.0,
                Abundance = 0.0,
                Category = 1,
                Configuration = "[Ar] 3d10 4s2 4p6",
                Electrons = "2,8,18,8",
                Unstable = false,
            },
            new Element {
                Number = 37,
                Symbol = "Rb",
                Group = 1,
                Period = 5,
                Block = "s",
                Weight = 85.4678,
                Density = 1.532,
                Melt = 312.46,
                Boil = 961.0,
                Heat = 0.363,
                Negativity = 0.82,
                Abundance = 90.0,
                Category = 2,
                Configuration = "[Kr] 5s1",
                Electrons = "2,8,18,8,1",
                Unstable = false,
            },
            new Element {
                Number = 38,
                Symbol = "Sr",
                Group = 2,
                Period = 5,
                Block = "s",
                Weight = 87.62,
                Density = 2.64,
                Melt = 1050.0,
                Boil = 1655.0,
                Heat = 0.301,
                Negativity = 0.95,
                Abundance = 370.0,
                Category = 3,
                Configuration = "[Kr] 5s2",
                Electrons = "2,8,18,8,2",
                Unstable = false,
            },
            new Element {
                Number = 39,
                Symbol = "Y",
                Group = 3,
                Period = 5,
                Block = "d",
                Weight = 88.90585,
                Density = 4.469,
                Melt = 1799.0,
                Boil = 3609.0,
                Heat = 0.298,
                Negativity = 1.22,
                Abundance = 33.0,
                Category = 7,
                Configuration = "[Kr] 4d1 5s2",
                Electrons = "2,8,18,9,2",
                Unstable = false,
            },
            new Element {
                Number = 40,
                Symbol = "Zr",
                Group = 4,
                Period = 5,
                Block = "d",
                Weight = 91.224,
                Density = 6.506,
                Melt = 2128.0,
                Boil = 4682.0,
                Heat = 0.278,
                Negativity = 1.33,
                Abundance = 165.0,
                Category = 7,
                Configuration = "[Kr] 4d2 5s2",
                Electrons = "2,8,18,10,2",
                Unstable = false,
            },
            new Element {
                Number = 41,
                Symbol = "Nb",
                Group = 5,
                Period = 5,
                Block = "d",
                Weight = 92.90638,
                Density = 8.57,
                Melt = 2750.0,
                Boil = 5017.0,
                Heat = 0.265,
                Negativity = 1.6,
                Abundance = 20.0,
                Category = 7,
                Configuration = "[Kr] 4d4 5s1",
                Electrons = "2,8,18,12,1",
                Unstable = false,
            },
            new Element {
                Number = 42,
                Symbol = "Mo",
                Group = 6,
                Period = 5,
                Block = "d",
                Weight = 95.96,
                Density = 10.22,
                Melt = 2896.0,
                Boil = 4912.0,
                Heat = 0.251,
                Negativity = 2.16,
                Abundance = 1.2,
                Category = 7,
                Configuration = "[Kr] 4d5 5s1",
                Electrons = "2,8,18,13,1",
                Unstable = false,
            },
            new Element {
                Number = 43,
                Symbol = "Tc",
                Group = 7,
                Period = 5,
                Block = "d",
                Weight = 98.0,
                Density = 11.5,
                Melt = 2430.0,
                Boil = 4538.0,
                Heat = null,
                Negativity = 1.9,
                Abundance = 0.0,
                Category = 7,
                Configuration = "[Kr] 4d5 5s2",
                Electrons = "2,8,18,13,2",
                Unstable = true,
            },
            new Element {
                Number = 44,
                Symbol = "Ru",
                Group = 8,
                Period = 5,
                Block = "d",
                Weight = 101.07,
                Density = 12.37,
                Melt = 2607.0,
                Boil = 4423.0,
                Heat = 0.238,
                Negativity = 2.2,
                Abundance = 0.001,
                Category = 7,
                Configuration = "[Kr] 4d7 5s1",
                Electrons = "2,8,18,15,1",
                Unstable = false,
            },
            new Element {
                Number = 45,
                Symbol = "Rh",
                Group = 9,
                Period = 5,
                Block = "d",
                Weight = 102.9055,
                Density = 12.41,
                Melt = 2237.0,
                Boil = 3968.0,
                Heat = 0.243,
                Negativity = 2.28,
                Abundance = 0.001,
                Category = 7,
                Configuration = "[Kr] 4d8 5s1",
                Electrons = "2,8,18,16,1",
                Unstable = false,
            },
            new Element {
                Number = 46,
                Symbol = "Pd",
                Group = 10,
                Period = 5,
                Block = "d",
                Weight = 106.42,
                Density = 12.02,
                Melt = 1828.05,
                Boil = 3236.0,
                Heat = 0.244,
                Negativity = 2.2,
                Abundance = 0.015,
                Category = 7,
                Configuration = "[Kr] 4d10",
                Electrons = "2,8,18,18",
                Unstable = false,
            },
            new Element {
                Number = 47,
                Symbol = "Ag",
                Group = 11,
                Period = 5,
                Block = "d",
                Weight = 107.8682,
                Density = 10.501,
                Melt = 1234.93,
                Boil = 2435.0,
                Heat = 0.235,
                Negativity = 1.93,
                Abundance = 0.075,
                Category = 7,
                Configuration = "[Kr] 4d10 5s1",
                Electrons = "2,8,18,18,1",
                Unstable = false,
            },
            new Element {
                Number = 48,
                Symbol = "Cd",
                Group = 12,
                Period = 5,
                Block = "d",
                Weight = 112.411,
                Density = 8.69,
                Melt = 594.22,
                Boil = 1040.0,
                Heat = 0.232,
                Negativity = 1.69,
                Abundance = 0.159,
                Category = 7,
                Configuration = "[Kr] 4d10 5s2",
                Electrons = "2,8,18,18,2",
                Unstable = false,
            },
            new Element {
                Number = 49,
                Symbol = "In",
                Group = 13,
                Period = 5,
                Block = "p",
                Weight = 114.818,
                Density = 7.31,
                Melt = 429.75,
                Boil = 2345.0,
                Heat = 0.233,
                Negativity = 1.78,
                Abundance = 0.25,
                Category = 6,
                Configuration = "[Kr] 4d10 5s2 5p1",
                Electrons = "2,8,18,18,3",
                Unstable = false,
            },
            new Element {
                Number = 50,
                Symbol = "Sn",
                Group = 14,
                Period = 5,
                Block = "p",
                Weight = 118.71,
                Density = 7.287,
                Melt = 505.08,
                Boil = 2875.0,
                Heat = 0.228,
                Negativity = 1.96,
                Abundance = 2.3,
                Category = 6,
                Configuration = "[Kr] 4d10 5s2 5p2",
                Electrons = "2,8,18,18,4",
                Unstable = false,
            },
            new Element {
                Number = 51,
                Symbol = "Sb",
                Group = 15,
                Period = 5,
                Block = "p",
                Weight = 121.76,
                Density = 6.685,
                Melt = 903.78,
                Boil = 1860.0,
                Heat = 0.207,
                Negativity = 2.05,
                Abundance = 0.2,
                Category = 4,
                Configuration = "[Kr] 4d10 5s2 5p3",
                Electrons = "2,8,18,18,5",
                Unstable = false,
            },
            new Element {
                Number = 52,
                Symbol = "Te",
                Group = 16,
                Period = 5,
                Block = "p",
                Weight = 127.6,
                Density = 6.232,
                Melt = 722.66,
                Boil = 1261.0,
                Heat = 0.202,
                Negativity = 2.1,
                Abundance = 0.001,
                Category = 4,
                Configuration = "[Kr] 4d10 5s2 5p4",
                Electrons = "2,8,18,18,6",
                Unstable = false,
            },
            new Element {
                Number = 53,
                Symbol = "I",
                Group = 17,
                Period = 5,
                Block = "p",
                Weight = 126.90447,
                Density = 4.93,
                Melt = 386.85,
                Boil = 457.4,
                Heat = 0.214,
                Negativity = 2.66,
                Abundance = 0.45,
                Category = 5,
                Configuration = "[Kr] 4d10 5s2 5p5",
                Electrons = "2,8,18,18,7",
                Unstable = false,
            },
            new Element {
                Number = 54,
                Symbol = "Xe",
                Group = 18,
                Period = 5,
                Block = "p",
                Weight = 131.293,
                Density = 0.005887,
                Melt = 161.4,
                Boil = 165.03,
                Heat = 0.158,
                Negativity = 2.6,
                Abundance = 0.0,
                Category = 1,
                Configuration = "[Kr] 4d10 5s2 5p6",
                Electrons = "2,8,18,18,8",
                Unstable = false,
            },
            new Element {
                Number = 55,
                Symbol = "Cs",
                Group = 1,
                Period = 6,
                Block = "s",
                Weight = 132.9054519,
                Density = 1.873,
                Melt = 301.59,
                Boil = 944.0,
                Heat = 0.242,
                Negativity = 0.79,
                Abundance = 3.0,
                Category = 2,
                Configuration = "[Xe] 6s1",
                Electrons = "2,8,18,18,8,1",
                Unstable = false,
            },
            new Element {
                Number = 56,
                Symbol = "Ba",
                Group = 2,
                Period = 6,
                Block = "s",
                Weight = 137.327,
                Density = 3.594,
                Melt = 1000.0,
                Boil = 2170.0,
                Heat = 0.204,
                Negativity = 0.89,
                Abundance = 425.0,
                Category = 3,
                Configuration = "[Xe] 6s2",
                Electrons = "2,8,18,18,8,2",
                Unstable = false,
            },
            new Element {
                Number = 57,
                Symbol = "La",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 138.90547,
                Density = 6.145,
                Melt = 1193.0,
                Boil = 3737.0,
                Heat = 0.195,
                Negativity = 1.1,
                Abundance = 39.0,
                Category = 8,
                Configuration = "[Xe] 5d1 6s2",
                Electrons = "2,8,18,18,9,2",
                Unstable = false,
            },
            new Element {
                Number = 58,
                Symbol = "Ce",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 140.116,
                Density = 6.77,
                Melt = 1068.0,
                Boil = 3716.0,
                Heat = 0.192,
                Negativity = 1.12,
                Abundance = 66.5,
                Category = 8,
                Configuration = "[Xe] 4f1 5d1 6s2",
                Electrons = "2,8,18,19,9,2",
                Unstable = false,
            },
            new Element {
                Number = 59,
                Symbol = "Pr",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 140.90765,
                Density = 6.773,
                Melt = 1208.0,
                Boil = 3793.0,
                Heat = 0.193,
                Negativity = 1.13,
                Abundance = 9.2,
                Category = 8,
                Configuration = "[Xe] 4f3 6s2",
                Electrons = "2,8,18,21,8,2",
                Unstable = false,
            },
            new Element {
                Number = 60,
                Symbol = "Nd",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 144.242,
                Density = 7.007,
                Melt = 1297.0,
                Boil = 3347.0,
                Heat = 0.19,
                Negativity = 1.14,
                Abundance = 41.5,
                Category = 8,
                Configuration = "[Xe] 4f4 6s2",
                Electrons = "2,8,18,22,8,2",
                Unstable = false,
            },
            new Element {
                Number = 61,
                Symbol = "Pm",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 145.0,
                Density = 7.26,
                Melt = 1315.0,
                Boil = 3273.0,
                Heat = null,
                Negativity = null,
                Abundance = 0.0,
                Category = 8,
                Configuration = "[Xe] 4f5 6s2",
                Electrons = "2,8,18,23,8,2",
                Unstable = true,
            },
            new Element {
                Number = 62,
                Symbol = "Sm",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 150.36,
                Density = 7.52,
                Melt = 1345.0,
                Boil = 2067.0,
                Heat = 0.197,
                Negativity = 1.17,
                Abundance = 7.05,
                Category = 8,
                Configuration = "[Xe] 4f6 6s2",
                Electrons = "2,8,18,24,8,2",
                Unstable = false,
            },
            new Element {
                Number = 63,
                Symbol = "Eu",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 151.964,
                Density = 5.243,
                Melt = 1099.0,
                Boil = 1802.0,
                Heat = 0.182,
                Negativity = 1.2,
                Abundance = 2.0,
                Category = 8,
                Configuration = "[Xe] 4f7 6s2",
                Electrons = "2,8,18,25,8,2",
                Unstable = false,
            },
            new Element {
                Number = 64,
                Symbol = "Gd",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 157.25,
                Density = 7.895,
                Melt = 1585.0,
                Boil = 3546.0,
                Heat = 0.236,
                Negativity = 1.2,
                Abundance = 6.2,
                Category = 8,
                Configuration = "[Xe] 4f7 5d1 6s2",
                Electrons = "2,8,18,25,9,2",
                Unstable = false,
            },
            new Element {
                Number = 65,
                Symbol = "Tb",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 158.92535,
                Density = 8.229,
                Melt = 1629.0,
                Boil = 3503.0,
                Heat = 0.182,
                Negativity = 1.2,
                Abundance = 1.2,
                Category = 8,
                Configuration = "[Xe] 4f9 6s2",
                Electrons = "2,8,18,27,8,2",
                Unstable = false,
            },
            new Element {
                Number = 66,
                Symbol = "Dy",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 162.5,
                Density = 8.55,
                Melt = 1680.0,
                Boil = 2840.0,
                Heat = 0.17,
                Negativity = 1.22,
                Abundance = 5.2,
                Category = 8,
                Configuration = "[Xe] 4f10 6s2",
                Electrons = "2,8,18,28,8,2",
                Unstable = false,
            },
            new Element {
                Number = 67,
                Symbol = "Ho",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 164.93032,
                Density = 8.795,
                Melt = 1734.0,
                Boil = 2993.0,
                Heat = 0.165,
                Negativity = 1.23,
                Abundance = 1.3,
                Category = 8,
                Configuration = "[Xe] 4f11 6s2",
                Electrons = "2,8,18,29,8,2",
                Unstable = false,
            },
            new Element {
                Number = 68,
                Symbol = "Er",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 167.259,
                Density = 9.066,
                Melt = 1802.0,
                Boil = 3141.0,
                Heat = 0.168,
                Negativity = 1.24,
                Abundance = 3.5,
                Category = 8,
                Configuration = "[Xe] 4f12 6s2",
                Electrons = "2,8,18,30,8,2",
                Unstable = false,
            },
            new Element {
                Number = 69,
                Symbol = "Tm",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 168.93421,
                Density = 9.321,
                Melt = 1818.0,
                Boil = 2223.0,
                Heat = 0.16,
                Negativity = 1.25,
                Abundance = 0.52,
                Category = 8,
                Configuration = "[Xe] 4f13 6s2",
                Electrons = "2,8,18,31,8,2",
                Unstable = false,
            },
            new Element {
                Number = 70,
                Symbol = "Yb",
                Group = 0,
                Period = 6,
                Block = "f",
                Weight = 173.054,
                Density = 6.965,
                Melt = 1097.0,
                Boil = 1469.0,
                Heat = 0.155,
                Negativity = 1.1,
                Abundance = 3.2,
                Category = 8,
                Configuration = "[Xe] 4f14 6s2",
                Electrons = "2,8,18,32,8,2",
                Unstable = false,
            },
            new Element {
                Number = 71,
                Symbol = "Lu",
                Group = 0,
                Period = 6,
                Block = "d",
                Weight = 174.9668,
                Density = 9.84,
                Melt = 1925.0,
                Boil = 3675.0,
                Heat = 0.154,
                Negativity = 1.27,
                Abundance = 0.8,
                Category = 8,
                Configuration = "[Xe] 4f14 5d1 6s2",
                Electrons = "2,8,18,32,9,2",
                Unstable = false,
            },
            new Element {
                Number = 72,
                Symbol = "Hf",
                Group = 4,
                Period = 6,
                Block = "d",
                Weight = 178.49,
                Density = 13.31,
                Melt = 2506.0,
                Boil = 4876.0,
                Heat = 0.144,
                Negativity = 1.3,
                Abundance = 3.0,
                Category = 7,
                Configuration = "[Xe] 4f14 5d2 6s2",
                Electrons = "2,8,18,32,10,2",
                Unstable = false,
            },
            new Element {
                Number = 73,
                Symbol = "Ta",
                Group = 5,
                Period = 6,
                Block = "d",
                Weight = 180.94788,
                Density = 16.654,
                Melt = 3290.0,
                Boil = 5731.0,
                Heat = 0.14,
                Negativity = 1.5,
                Abundance = 2.0,
                Category = 7,
                Configuration = "[Xe] 4f14 5d3 6s2",
                Electrons = "2,8,18,32,11,2",
                Unstable = false,
            },
            new Element {
                Number = 74,
                Symbol = "W",
                Group = 6,
                Period = 6,
                Block = "d",
                Weight = 183.84,
                Density = 19.25,
                Melt = 3695.0,
                Boil = 5828.0,
                Heat = 0.132,
                Negativity = 2.36,
                Abundance = 1.3,
                Category = 7,
                Configuration = "[Xe] 4f14 5d4 6s2",
                Electrons = "2,8,18,32,12,2",
                Unstable = false,
            },
            new Element {
                Number = 75,
                Symbol = "Re",
                Group = 7,
                Period = 6,
                Block = "d",
                Weight = 186.207,
                Density = 21.02,
                Melt = 3459.0,
                Boil = 5869.0,
                Heat = 0.137,
                Negativity = 1.9,
                Abundance = 0.0,
                Category = 7,
                Configuration = "[Xe] 4f14 5d5 6s2",
                Electrons = "2,8,18,32,13,2",
                Unstable = false,
            },
            new Element {
                Number = 76,
                Symbol = "Os",
                Group = 8,
                Period = 6,
                Block = "d",
                Weight = 190.23,
                Density = 22.61,
                Melt = 3306.0,
                Boil = 5285.0,
                Heat = 0.13,
                Negativity = 2.2,
                Abundance = 0.002,
                Category = 7,
                Configuration = "[Xe] 4f14 5d6 6s2",
                Electrons = "2,8,18,32,14,2",
                Unstable = false,
            },
            new Element {
                Number = 77,
                Symbol = "Ir",
                Group = 9,
                Period = 6,
                Block = "d",
                Weight = 192.217,
                Density = 22.56,
                Melt = 2719.0,
                Boil = 4701.0,
                Heat = 0.131,
                Negativity = 2.2,
                Abundance = 0.001,
                Category = 7,
                Configuration = "[Xe] 4f14 5d7 6s2",
                Electrons = "2,8,18,32,15,2",
                Unstable = false,
            },
            new Element {
                Number = 78,
                Symbol = "Pt",
                Group = 10,
                Period = 6,
                Block = "d",
                Weight = 195.084,
                Density = 21.46,
                Melt = 2041.4,
                Boil = 4098.0,
                Heat = 0.133,
                Negativity = 2.28,
                Abundance = 0.005,
                Category = 7,
                Configuration = "[Xe] 4f14 5d9 6s1",
                Electrons = "2,8,18,32,17,1",
                Unstable = false,
            },
            new Element {
                Number = 79,
                Symbol = "Au",
                Group = 11,
                Period = 6,
                Block = "d",
                Weight = 196.966569,
                Density = 19.282,
                Melt = 1337.33,
                Boil = 3129.0,
                Heat = 0.129,
                Negativity = 2.54,
                Abundance = 0.004,
                Category = 7,
                Configuration = "[Xe] 4f14 5d10 6s1",
                Electrons = "2,8,18,32,18,1",
                Unstable = false,
            },
            new Element {
                Number = 80,
                Symbol = "Hg",
                Group = 12,
                Period = 6,
                Block = "d",
                Weight = 200.59,
                Density = 13.5336,
                Melt = 234.32,
                Boil = 629.88,
                Heat = 0.14,
                Negativity = 2.0,
                Abundance = 0.085,
                Category = 7,
                Configuration = "[Xe] 4f14 5d10 6s2",
                Electrons = "2,8,18,32,18,2",
                Unstable = false,
            },
            new Element {
                Number = 81,
                Symbol = "Tl",
                Group = 13,
                Period = 6,
                Block = "p",
                Weight = 204.3833,
                Density = 11.85,
                Melt = 577.0,
                Boil = 1746.0,
                Heat = 0.129,
                Negativity = 1.62,
                Abundance = 0.85,
                Category = 6,
                Configuration = "[Xe] 4f14 5d10 6s2 6p1",
                Electrons = "2,8,18,32,18,3",
                Unstable = false,
            },
            new Element {
                Number = 82,
                Symbol = "Pb",
                Group = 14,
                Period = 6,
                Block = "p",
                Weight = 207.2,
                Density = 11.342,
                Melt = 600.61,
                Boil = 2022.0,
                Heat = 0.129,
                Negativity = 2.33,
                Abundance = 14.0,
                Category = 6,
                Configuration = "[Xe] 4f14 5d10 6s2 6p2",
                Electrons = "2,8,18,32,18,4",
                Unstable = false,
            },
            new Element {
                Number = 83,
                Symbol = "Bi",
                Group = 15,
                Period = 6,
                Block = "p",
                Weight = 208.9804,
                Density = 9.807,
                Melt = 544.7,
                Boil = 1837.0,
                Heat = 0.122,
                Negativity = 2.02,
                Abundance = 0.009,
                Category = 6,
                Configuration = "[Xe] 4f14 5d10 6s2 6p3",
                Electrons = "2,8,18,32,18,5",
                Unstable = false,
            },
            new Element {
                Number = 84,
                Symbol = "Po",
                Group = 16,
                Period = 6,
                Block = "p",
                Weight = 210.0,
                Density = 9.32,
                Melt = 527.0,
                Boil = 1235.0,
                Heat = null,
                Negativity = 2.0,
                Abundance = 0.0,
                Category = 4,
                Configuration = "[Xe] 4f14 5d10 6s2 6p4",
                Electrons = "2,8,18,32,18,6",
                Unstable = true,
            },
            new Element {
                Number = 85,
                Symbol = "At",
                Group = 17,
                Period = 6,
                Block = "p",
                Weight = 210.0,
                Density = 7.0,
                Melt = 575.0,
                Boil = 610.0,
                Heat = null,
                Negativity = 2.2,
                Abundance = 0.0,
                Category = 5,
                Configuration = "[Xe] 4f14 5d10 6s2 6p5",
                Electrons = "2,8,18,32,18,7",
                Unstable = true,
            },
            new Element {
                Number = 86,
                Symbol = "Rn",
                Group = 18,
                Period = 6,
                Block = "p",
                Weight = 222.0,
                Density = 0.00973,
                Melt = 202.0,
                Boil = 211.3,
                Heat = 0.094,
                Negativity = null,
                Abundance = 0.0,
                Category = 1,
                Configuration = "[Xe] 4f14 5d10 6s2 6p6",
                Electrons = "2,8,18,32,18,8",
                Unstable = true,
            },
            new Element {
                Number = 87,
                Symbol = "Fr",
                Group = 1,
                Period = 7,
                Block = "s",
                Weight = 223.0,
                Density = 1.87,
                Melt = 300.0,
                Boil = 950.0,
                Heat = null,
                Negativity = 0.7,
                Abundance = 0.0,
                Category = 2,
                Configuration = "[Rn] 7s1",
                Electrons = "2,8,18,32,18,8,1",
                Unstable = true,
            },
            new Element {
                Number = 88,
                Symbol = "Ra",
                Group = 2,
                Period = 7,
                Block = "s",
                Weight = 226.0,
                Density = 5.5,
                Melt = 973.0,
                Boil = 2010.0,
                Heat = null,
                Negativity = 0.9,
                Abundance = 0.0,
                Category = 3,
                Configuration = "[Rn] 7s2",
                Electrons = "2,8,18,32,18,8,2",
                Unstable = true,
            },
            new Element {
                Number = 89,
                Symbol = "Ac",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 227.0,
                Density = 10.07,
                Melt = 1323.0,
                Boil = 3471.0,
                Heat = 0.12,
                Negativity = 1.1,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 6d1 7s2",
                Electrons = "2,8,18,32,18,9,2",
                Unstable = true,
            },
            new Element {
                Number = 90,
                Symbol = "Th",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 232.03806,
                Density = 11.72,
                Melt = 2115.0,
                Boil = 5061.0,
                Heat = 0.113,
                Negativity = 1.3,
                Abundance = 9.6,
                Category = 9,
                Configuration = "[Rn] 6d2 7s2",
                Electrons = "2,8,18,32,18,10,2",
                Unstable = false,
            },
            new Element {
                Number = 91,
                Symbol = "Pa",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 231.03588,
                Density = 15.37,
                Melt = 1841.0,
                Boil = 4273.0,
                Heat = null,
                Negativity = 1.5,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f2 6d1 7s2",
                Electrons = "2,8,18,32,20,9,2",
                Unstable = false,
            },
            new Element {
                Number = 92,
                Symbol = "U",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 238.02891,
                Density = 18.95,
                Melt = 1405.3,
                Boil = 4404.0,
                Heat = 0.116,
                Negativity = 1.38,
                Abundance = 2.7,
                Category = 9,
                Configuration = "[Rn] 5f3 6d1 7s2",
                Electrons = "2,8,18,32,21,9,2",
                Unstable = false,
            },
            new Element {
                Number = 93,
                Symbol = "Np",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 237.0,
                Density = 20.45,
                Melt = 917.0,
                Boil = 4273.0,
                Heat = null,
                Negativity = 1.36,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f4 6d1 7s2",
                Electrons = "2,8,18,32,22,9,2",
                Unstable = true,
            },
            new Element {
                Number = 94,
                Symbol = "Pu",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 244.0,
                Density = 19.84,
                Melt = 912.5,
                Boil = 3501.0,
                Heat = null,
                Negativity = 1.28,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f6 7s2",
                Electrons = "2,8,18,32,24,8,2",
                Unstable = true,
            },
            new Element {
                Number = 95,
                Symbol = "Am",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 243.0,
                Density = 13.69,
                Melt = 1449.0,
                Boil = 2880.0,
                Heat = null,
                Negativity = 1.3,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f7 7s2",
                Electrons = "2,8,18,32,25,8,2",
                Unstable = true,
            },
            new Element {
                Number = 96,
                Symbol = "Cm",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 247.0,
                Density = 13.51,
                Melt = 1613.0,
                Boil = 3383.0,
                Heat = null,
                Negativity = 1.3,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f7 6d1 7s2",
                Electrons = "2,8,18,32,25,9,2",
                Unstable = true,
            },
            new Element {
                Number = 97,
                Symbol = "Bk",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 247.0,
                Density = 14.79,
                Melt = 1323.0,
                Boil = 983.0,
                Heat = null,
                Negativity = 1.3,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f9 7s2",
                Electrons = "2,8,18,32,27,8,2",
                Unstable = true,
            },
            new Element {
                Number = 98,
                Symbol = "Cf",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 251.0,
                Density = 15.1,
                Melt = 1173.0,
                Boil = 1173.0,
                Heat = null,
                Negativity = 1.3,
                Abundance = 0.0,
                Category = 9,
                Configuration = "[Rn] 5f10 7s2",
                Electrons = "2,8,18,32,28,8,2",
                Unstable = true,
            },
            new Element {
                Number = 99,
                Symbol = "Es",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 252.0,
                Density = 13.5,
                Melt = 1133.0,
                Boil = null,
                Heat = null,
                Negativity = 1.3,
                Abundance = null,
                Category = 9,
                Configuration = "[Rn] 5f11 7s2",
                Electrons = "2,8,18,32,29,8,2",
                Unstable = true,
            },
            new Element {
                Number = 100,
                Symbol = "Fm",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 257.0,
                Density = null,
                Melt = 1800.0,
                Boil = null,
                Heat = null,
                Negativity = 1.3,
                Abundance = null,
                Category = 9,
                Configuration = "[Rn] 5f12 7s2",
                Electrons = "2,8,18,32,30,8,2",
                Unstable = true,
            },
            new Element {
                Number = 101,
                Symbol = "Md",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 258.0,
                Density = null,
                Melt = 1100.0,
                Boil = null,
                Heat = null,
                Negativity = 1.3,
                Abundance = null,
                Category = 9,
                Configuration = "[Rn] 5f13 7s2",
                Electrons = "2,8,18,32,31,8,2",
                Unstable = true,
            },
            new Element {
                Number = 102,
                Symbol = "No",
                Group = 0,
                Period = 7,
                Block = "f",
                Weight = 259.0,
                Density = null,
                Melt = 1100.0,
                Boil = null,
                Heat = null,
                Negativity = 1.3,
                Abundance = null,
                Category = 9,
                Configuration = "[Rn] 5f14 7s2",
                Electrons = "2,8,18,32,32,8,2",
                Unstable = true,
            },
            new Element {
                Number = 103,
                Symbol = "Lr",
                Group = 0,
                Period = 7,
                Block = "d",
                Weight = 262.0,
                Density = null,
                Melt = 1900.0,
                Boil = null,
                Heat = null,
                Negativity = 1.3,
                Abundance = null,
                Category = 9,
                Configuration = "[Rn] 5f14 7s2 7p1",
                Electrons = "2,8,18,32,32,8,3",
                Unstable = true,
            },
            new Element {
                Number = 104,
                Symbol = "Rf",
                Group = 4,
                Period = 7,
                Block = "d",
                Weight = 267.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 5f14 6d2 7s2",
                Electrons = "2,8,18,32,32,10,2",
                Unstable = true,
            },
            new Element {
                Number = 105,
                Symbol = "Db",
                Group = 5,
                Period = 7,
                Block = "d",
                Weight = 268.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 5f14 6d3 7s2",
                Electrons = "2,8,18,32,32,11,2",
                Unstable = true,
            },
            new Element {
                Number = 106,
                Symbol = "Sg",
                Group = 6,
                Period = 7,
                Block = "d",
                Weight = 269.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 7s2 5f14 6d4",
                Electrons = "2,8,18,32,32,12,2",
                Unstable = true,
            },
            new Element {
                Number = 107,
                Symbol = "Bh",
                Group = 7,
                Period = 7,
                Block = "d",
                Weight = 270.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 5f14 6d5 7s2",
                Electrons = "2,8,18,32,32,13,2",
                Unstable = true,
            },
            new Element {
                Number = 108,
                Symbol = "Hs",
                Group = 8,
                Period = 7,
                Block = "d",
                Weight = 269.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 5f14 6d6 7s2",
                Electrons = "2,8,18,32,32,14,2",
                Unstable = true,
            },
            new Element {
                Number = 109,
                Symbol = "Mt",
                Group = 9,
                Period = 7,
                Block = "d",
                Weight = 278.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 7s2 5f14 6d7",
                Electrons = "2,8,18,32,32,15,2",
                Unstable = true,
            },
            new Element {
                Number = 110,
                Symbol = "Ds",
                Group = 10,
                Period = 7,
                Block = "d",
                Weight = 281.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 7s2 5f14 6d8",
                Electrons = "2,8,18,32,32,17,1",
                Unstable = true,
            },
            new Element {
                Number = 111,
                Symbol = "Rg",
                Group = 11,
                Period = 7,
                Block = "d",
                Weight = 281.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 5f14 6d9 7s2",
                Electrons = "2,8,18,32,32,18,1",
                Unstable = true,
            },
            new Element {
                Number = 112,
                Symbol = "Cn",
                Group = 12,
                Period = 7,
                Block = "d",
                Weight = 285.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 7,
                Configuration = "[Rn] 5f14 6d10 7s2",
                Electrons = "2,8,18,32,32,18,2",
                Unstable = true,
            },
            new Element {
                Number = 113,
                Symbol = "Nh",
                Group = 13,
                Period = 7,
                Block = "p",
                Weight = 286.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 6,
                Configuration = "[Rn] 5f14 6d10 7s2 7p1",
                Electrons = "2,8,18,32,32,18,3",
                Unstable = true,
            },
            new Element {
                Number = 114,
                Symbol = "Fl",
                Group = 14,
                Period = 7,
                Block = "p",
                Weight = 289.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 6,
                Configuration = "[Rn] 5f14 6d10 7s2 7p2",
                Electrons = "2,8,18,32,32,18,4",
                Unstable = true,
            },
            new Element {
                Number = 115,
                Symbol = "Mc",
                Group = 15,
                Period = 7,
                Block = "p",
                Weight = 288.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 6,
                Configuration = "[Rn] 5f14 6d10 7s2 7p3",
                Electrons = "2,8,18,32,32,18,5",
                Unstable = true,
            },
            new Element {
                Number = 116,
                Symbol = "Lv",
                Group = 16,
                Period = 7,
                Block = "p",
                Weight = 293.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 6,
                Configuration = "[Rn] 5f14 6d10 7s2 7p4",
                Electrons = "2,8,18,32,32,18,6",
                Unstable = true,
            },
            new Element {
                Number = 117,
                Symbol = "Ts",
                Group = 17,
                Period = 7,
                Block = "p",
                Weight = 294.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 5,
                Configuration = "[Rn] 5f14 6d10 7s2 7p5",
                Electrons = "2,8,18,32,32,18,7",
                Unstable = true,
            },
            new Element {
                Number = 118,
                Symbol = "Og",
                Group = 18,
                Period = 7,
                Block = "p",
                Weight = 294.0,
                Density = null,
                Melt = null,
                Boil = null,
                Heat = null,
                Negativity = null,
                Abundance = null,
                Category = 1,
                Configuration = "[Rn] 5f14 6d10 7s2 7p6",
                Electrons = "2,8,18,32,32,18,8",
                Unstable = true,
            },
        };
    }
}
